### ISSUE TITLE
Weak encryption [ risk: medium ]

### ISSUE THREAD

**Issue by CoolerVoid** [Cerbersec/Ares#1]
Very cool project, I have one suggestion.

CBC mode has a risk of collision, considered a weak security mode for AES context; my suggestion is to use mode GCM instead of CBC.
https://github.com/Cerbersec/Ares/blob/main/Ares/Cryptor/aes.c#L501

Reference:
https://vulncat.fortify.com/en/detail?id=desc.semantic.cpp.weak_encryption_insecure_mode_of_operation

**Comment by Cerbersec** [comment]
Thanks for the feedback! The encryption serves its purpose for obfuscation and is not meant to be secure, since the encryption key is hardcoded in the binary and can be retrieved by means of a simple String search.
