### ISSUE TITLE
resource.h not found

### ISSUE THREAD

**Issue by MaorSabag** [Cerbersec/Ares#3]
Hey, when compiling Ares, I get an error of "resource.h" not found, there is no resource.h in any folder.

**Comment by Cerbersec** [comment]
resource.h is automatically generated by Visual Studio when you add the payload as a resource.
https://docs.microsoft.com/en-us/visualstudio/sharepoint/how-to-add-a-resource-file?view=vs-2022

**Comment by GeorgePatsias** [comment]
Hello, I have the same issue, can you please elaborate more on how to add the resource.h because the microsoft documentation is not helping much. Thanks
